/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifnmg.poo.trabalhos.datapersistence.graphicInterface;

import br.edu.ifnmg.poo.trabalhos.datapersistence.credential.Credential;
import br.edu.ifnmg.poo.trabalhos.datapersistence.credential.CredentialDao;
import br.edu.ifnmg.poo.trabalhos.datapersistence.user.User;
import java.awt.Color;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 * @author Gabriel Davi
 * @author Luiz
 * @author Lucas Santos 
 *
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
      
    private static boolean retornoTela = false; 
    private static String usernameLogado; 
    private static int tentativaAcesso = 0;
    
    private final String usuarioText = "Usuario";       // Texto que aparece na label txtUsuario
    private final String passwordText = "@1457857521";  // Texto que aparece na label txtSenha
    private final Color colorNotSelected = new Color(102, 102, 102); // Cor do texto não selecionado
    private final Color colorSelected = new Color(0, 0, 0);         // Cor do texto selecionado
    
    
    private final Color colorWelcomeNotSelected = new Color(239,239,239);   // Cor do texto boas vindas não selecionado 
    private final Color colorWelcomeSelected = new Color(255,255,255);      // Cor do texto boas vindas selecionado
    
    
    public Login() {
        initComponents();
        
        // Centraliza o jFrame
        this.setLocationRelativeTo(null);
        
        //Impede de ser Maximizado
        setResizable(false);
        
       // Iniicia erroLogin invisível;
       lblErroLogin.setVisible(false);
        
       // inicia esqueceuSenha invisivel;
       lblEsqueceuSenha.setVisible(false);
       
        jPanel1.requestFocus();
        
        txtUsuario.setText(usuarioText);
        txtSenha.setText(passwordText);
        
        
        if(retornoTela){
            String usuarioLogado = usernameLogado;
            txtUsuario.setText(usuarioLogado);
            txtSenha.requestFocus();
            txtSenha.setText("");
        }
      
    }
    
    private void exibirMenuPrincipal(User userLogado) {
        
        MenuPrincipal menuPrincipal = null;
        try {
            menuPrincipal = new MenuPrincipal(userLogado);
        } catch (Exception ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        menuPrincipal.setLocationRelativeTo(null);
        menuPrincipal.setVisible(true);
        setVisible(false);
        retornoTela = true;
        usernameLogado = userLogado.getCredential().getUsername();
        
    }
    
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblVindo = new javax.swing.JLabel();
        lblBem = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        lblErroLogin = new javax.swing.JLabel();
        lblEsqueceuSenha = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela de Login");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVindo.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        lblVindo.setForeground(new java.awt.Color(239, 239, 239));
        lblVindo.setText("VINDO");
        lblVindo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblVindoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblVindoMouseExited(evt);
            }
        });
        jPanel2.add(lblVindo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        lblBem.setFont(new java.awt.Font("Segoe UI", 1, 70)); // NOI18N
        lblBem.setForeground(new java.awt.Color(239, 239, 239));
        lblBem.setText("BEM");
        lblBem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblBemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblBemMouseExited(evt);
            }
        });
        jPanel2.add(lblBem, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel1.setText("Sistema de Gestão Bibliotecária");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 437, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 460));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Faça seu login");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuario.setForeground(new java.awt.Color(102, 102, 102));
        txtUsuario.setText("Usuário");
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtUsuarioPropertyChange(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 229, 30));

        txtSenha.setBackground(new java.awt.Color(255, 255, 255));
        txtSenha.setForeground(new java.awt.Color(0, 0, 0));
        txtSenha.setText("...........");
        txtSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSenhaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSenhaFocusLost(evt);
            }
        });
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 229, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("e vamos começar!");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, -1, -1));

        lblErroLogin.setForeground(new java.awt.Color(204, 0, 51));
        lblErroLogin.setText("Usuário ou senha incorretos");
        jPanel1.add(lblErroLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        lblEsqueceuSenha.setForeground(new java.awt.Color(0, 51, 204));
        lblEsqueceuSenha.setText("Se esqueceu a senha, contate um administrador");
        jPanel1.add(lblEsqueceuSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));

        btnEntrar.setBackground(new java.awt.Color(0, 0, 0));
        btnEntrar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        
    }//GEN-LAST:event_txtUsuarioMouseClicked

    private void txtUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusGained
        
        //lblErroLogin.setVisible(false);
        
        if(txtUsuario.getText().equals("") || txtUsuario.getText().equals(usuarioText)){
            txtUsuario.setText("");
            txtUsuario.setForeground(colorSelected);
        }
        
    }//GEN-LAST:event_txtUsuarioFocusGained

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        if(txtUsuario.getText().equals("")){
            txtUsuario.setText("Usuario");
            txtUsuario.setForeground(colorNotSelected);
        }
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusGained
        lblErroLogin.setVisible(false);
        char[] passwordChars = txtSenha.getPassword();
        String passwordString = new String(passwordChars);

        if (passwordString.equals("") || passwordString.equals(passwordText)) {
            txtSenha.setText("");
            txtSenha.setForeground(colorSelected);
        }
    }//GEN-LAST:event_txtSenhaFocusGained

    private void txtSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSenhaFocusLost
        char[] passwordChars = txtSenha.getPassword();
        String passwordString = new String(passwordChars);

        if (passwordString.equals("")) {
            txtSenha.setText(passwordText);
            txtSenha.setForeground(colorNotSelected);
        }
    }//GEN-LAST:event_txtSenhaFocusLost

    private void lblBemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBemMouseEntered
        lblBem.setForeground(colorWelcomeSelected);
    }//GEN-LAST:event_lblBemMouseEntered

    private void lblVindoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVindoMouseEntered
        lblVindo.setForeground(colorWelcomeSelected);
    }//GEN-LAST:event_lblVindoMouseEntered

    private void lblBemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBemMouseExited
        lblBem.setForeground(colorWelcomeNotSelected);
    }//GEN-LAST:event_lblBemMouseExited

    private void lblVindoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVindoMouseExited
        lblVindo.setForeground(colorWelcomeNotSelected);
    }//GEN-LAST:event_lblVindoMouseExited

    private void txtUsuarioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtUsuarioPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioPropertyChange

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        lblErroLogin.setVisible(false);
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        btnEntrar.doClick();
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        char[] password = txtSenha.getPassword();
        User userLogado = new User();
        Credential credential = new Credential();
        
        // Usuário ou Senha vazio
        if (password.length == 0 || txtUsuario.getText().isEmpty() || txtUsuario.getText().equals(usuarioText) || Arrays.equals(password, passwordText.toCharArray())) {
            return;
        }
        
        
        // Recebendo as credenciais
        try {
            credential.setPassword(new CredentialDao().crypPass(new String(password)));  
            credential.setUsername(txtUsuario.getText());
            
            
                        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "BtnEntrarActionPerformed: " + e, "Erro ao receber dados", ERROR);
        }
        
        
        // Tentativa de login
        userLogado = new CredentialDao().authenticate(credential);
            
        if(userLogado == null){
            
            txtSenha.setText("");
            txtUsuario.requestFocus();
            txtUsuario.selectAll();
            
            lblErroLogin.setVisible(true);
            tentativaAcesso++;
            
            if(tentativaAcesso >= 2){
                lblEsqueceuSenha.setVisible(true);
                
            }
            return;
        }
        
        
        // Verifica se o usuário é ativo
        if(!userLogado.getCredential().isEnabled()){
            JOptionPane.showMessageDialog(rootPane, "Usuário inativo - Contate o administrador do sistema");
            txtSenha.setText("");
            txtUsuario.requestFocus();
            return;
        }
        
        // Usuário logado
        userLogado.setCredential(credential);
        exibirMenuPrincipal(userLogado);
        tentativaAcesso = 0;
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblBem;
    private javax.swing.JLabel lblErroLogin;
    private javax.swing.JLabel lblEsqueceuSenha;
    private javax.swing.JLabel lblVindo;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
